update workflow

diff --git a/.github/workflows/build-aab.yml b/.github/workflows/build-aab.yml
--- a/.github/workflows/build-aab.yml
+++ b/.github/workflows/build-aab.yml
@@ -10,45 +10,45 @@ jobs:
     steps:
       - uses: actions/checkout@v3  
 
-      - name: Set up JDK 17  
-        uses: actions/setup-java@v3  
-        with:  
-          java-version: '17'  
-          distribution: 'temurin'  
-          cache: gradle  
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+          cache: gradle
 
       # 🔐 Create keystore from secrets
-    - name: Create keystore from secret
-      run: |
-        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/Star4droid.jks
-        
-        if [ -f app/Star4droid.jks ]; then
-          echo "Keystore file created successfully."
-          echo "KEYSTORE_FILE=$GITHUB_WORKSPACE/app/Star4droid.jks" >> $GITHUB_ENV
-          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
-          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
-          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
-        else
-          echo "Error: Keystore file was not created."
-          exit 1
-        fi
+      - name: Create keystore from secret
+        run: |
+          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/Star4droid.jks
+          
+          if [ -f app/Star4droid.jks ]; then
+            echo "Keystore file created successfully."
+            echo "KEYSTORE_FILE=$GITHUB_WORKSPACE/app/Star4droid.jks" >> $GITHUB_ENV
+            echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
+            echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
+            echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
+          else
+            echo "Error: Keystore file was not created."
+            exit 1
+          fi
 
-      - name: Setup Android NDK  
-        uses: nttld/setup-ndk@v1.5.0  
-        with:  
-          ndk-version: r28c  
+      - name: Setup Android NDK
+        uses: nttld/setup-ndk@v1.5.0
+        with:
+          ndk-version: r28c
 
-      - name: Grant execute permission for gradlew  
-        run: chmod +x gradlew  
+      - name: Grant execute permission for gradlew
+        run: chmod +x gradlew
 
-      - name: Build with Gradle  
-        run: ./gradlew clean bundleRelease  
+      - name: Build with Gradle
+        run: ./gradlew clean bundleRelease
 
-      - name: Upload AAB  
-        uses: actions/upload-artifact@v4  
-        with:  
-          name: engine.aab  
-          path: app/build/outputs/bundle/release/app-release.aab  
+      - name: Upload AAB
+        uses: actions/upload-artifact@v4
+        with:
+          name: engine.aab
+          path: app/build/outputs/bundle/release/app-release.aab
           retention-days: 90
           
       - name: List native .so files in AAB
