Update build-aab.yml

diff --git a/.github/workflows/build-aab.yml b/.github/workflows/build-aab.yml
--- a/.github/workflows/build-aab.yml
+++ b/.github/workflows/build-aab.yml
@@ -9,29 +9,29 @@ jobs:
 
     steps:
       - uses: actions/checkout@v3  
-      
-      # 🔐 Create keystore from secrets
-      - name: Create keystore from secret
-          run: |
-            echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > Star4droid.jks
-        
-            if [ -f Star4droid.jks ]; then
-              echo "Keystore file created successfully."
-              echo "KEYSTORE_FILE=Star4droid.jks" >> $GITHUB_ENV
-              echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
-              echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
-              echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
-            else
-              echo "Error: Keystore file was not created."
-              exit 1
-            fi
-            
+
       - name: Set up JDK 17  
         uses: actions/setup-java@v3  
         with:  
           java-version: '17'  
           distribution: 'temurin'  
           cache: gradle  
+
+      # 🔐 Create keystore from secrets
+      - name: Create keystore from secret
+        run: |
+          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > Star4droid.jks
+          
+          if [ -f Star4droid.jks ]; then
+            echo "Keystore file created successfully."
+            echo "KEYSTORE_FILE=Star4droid.jks" >> $GITHUB_ENV
+            echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
+            echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
+            echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
+          else
+            echo "Error: Keystore file was not created."
+            exit 1
+          fi
 
       - name: Setup Android NDK  
         uses: nttld/setup-ndk@v1.5.0  
